spring.application.name=mini-s3
spring.jpa.show-sql = true

spring.datasource.url = jdbc:postgresql://localhost:5432/minis3_db
spring.datasource.username = kaladin
spring.datasource.password = password
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size = 50MB
spring.servlet.multipart.max-request-size = 50MB
mini-s3.storage.location = uploads/
